#!/usr/bin/env python3

def parse(file):
  lines = [line.strip() for line in open(file)]
  return lines

# This function generated by ChatGPT
def find_start_of_packet(datastream, n):
    buffer = []

    for i in range(len(datastream)):
        buffer.append(datastream[i])
        if len(buffer) > n:
            buffer.pop(0)
        if len(buffer) == n and len(set(buffer)) == n:
            return i + 1

    return -1

def solve(file, part):
  lines = parse(file)
  n = 4 if part == 1 else 14

  for line in lines:
    print(find_start_of_packet(line, n))


solve('./example.txt', 1)
solve('./input.txt', 1)

solve('./example.txt', 2)
solve('./input.txt', 2)